name: Publish to npm

# ────────────────────────────────────────────────────────────────
# Dispara só quando houver push na branch main
# ────────────────────────────────────────────────────────────────
on:
  push:
    branches: [main]
    # Qualquer alteração relevante no código, package.json ou
    # neste próprio workflow dispara a action.
    paths:
      - '**/*.ts'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest

    # Leitura de código (contents) e permissão para publicar pacotes
    permissions:
      contents: read
      packages: write

    steps:
      # 1) Checkout do repositório
      - uses: actions/checkout@v4

      # 2) Prepara Node.js e cache do npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm

      # 3) Instala dependências exatamente como no package-lock
      - name: Install dependencies
        run: npm ci

      # 4) Compila TypeScript → pasta dist/
      - name: Build project
        run: npm run build

      # 5) Publica no npm (–access public para pacotes públicos)
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
