name: Publish

on:
  workflow_dispatch:         # publica apenas quando você clicar “Run workflow”
  release:                   # ou automaticamente quando criar uma tag v*
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      # instala dependências, compila, linta
      - run: |
          npm install
          npm run build
          npm run lint -c .eslintrc.prepublish.js nodes package.json

      # cria .npmrc temporário com o token
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # publica somente se for uma nova versão
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
