name: Publish package to npm

on:
  # publique manualmente ou no momento que preferir (tag, release, etc.)
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read        # checkout
      id-token: write       # carimbo de proveniência (--provenance)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: npm
          # se o pacote tiver um @scope, defina scope aqui
          # scope: '@seu-escopo'
          # o próprio action injeta NODE_AUTH_TOKEN a partir de secrets
          token: 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

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build       # compila + copia ícones

      - name: Lint (pré-publicação)
        run: npm run lint -c .eslintrc.prepublish.js nodes package.json

      - name: Publish to npm
        run: npm publish --access public --provenance
        env:
          # redundante, mas mantém compatibilidade se mudar o setup-node
          NODE_AUTH_TOKEN: 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
